name: app_date_picker_bottom_sheet
description: A customizable Flutter date picker bottom sheet with smooth animations, custom themes, and an easy-to-use API.
version: 0.1.1
homepage: https://github.com/yash27m/calender_sheet
repository: https://github.com/yash27m/calender_sheet
issue_tracker: https://github.com/yash27m/calender_sheet/issues

screenshots:
  - description: 'Calendar grid view date picker bottom sheet'
    path: screenshots/calendar_view.jpg
  - description: 'Month and year wheel picker selection view'
    path: screenshots/month_year_picker.jpg


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0